# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf39ea4dc554134779223752c7bf9875bb853bb83fdc83bd585ace73e30f86854f2fd6b6b8c129076cc0d189ff8620fb15fd1a4c95e5e8a2f25d7ea518098f4

test:
  secret_key_base: 73244dd95ceff3ecfa859938f7a50d4d6c1e627f3969c720dc1786dbdb7e28d2584b4b87738ca01c8fad2fcb9ca0ad152144690d7e42218433b103a56f77d09c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
